### PR TITLE
Second half of the repo import and small fixes.

### PR DESCRIPTION
**Pull request by tamasd**

### CODE REVIEW

**Comment by balazswmann** [comment]
The composer.json file is missing from the repo_sync module (it has a dependency: the redirect module).

EDIT: I guess the core devportal module should contain this ^ dependecy in its own composer.json, because we don't create composer.json files for sub-modules.

**Comment by balazswmann** [comment]
The configuration form cannot be reached from the UI (from the administration menu). Based on the config forms' path menu links should be somewhere under the "Devportal" menu link which also means that the module should depend on the devportal module.

**Comment by balazswmann** [comment]
Fatal error when visiting the admin/devportal/repo-sync/content path without any configuration (the module has just enabled):

`The website encountered an unexpected error. Please try again later.
TypeError: Argument 1 passed to Drupal\devportal_repo_sync\Service\Client::__construct() must be of the type string, null given, called in /home/balazswmann/public_html/sandbox8/web/modules/custom/devportal/modules/repo_sync/src/Service/RepoSyncConnector.php on line 44 in Drupal\devportal_repo_sync\Service\Client->__construct() (line 66 of modules/custom/devportal/modules/repo_sync/src/Service/Client.php).`

**Comment by balazswmann** [comment]
In the devportal.info.yml file the node dependency should be drupal:node And there is an unnecessary extra empty line at the end of this file.

**Review by balazswmann — APPROVED** [review]

**Review by lekob — APPROVED** [review]

**Pull request merged**
